load("@io_bazel_rules_go//go:def.bzl", "go_test")

exports_files([
    "go.mod",
    "go.sum",
])

go_test(
    name = "test",
    srcs = ["api_test.go"],
    deps = ["@com_github_latticebuild_graceproc//:graceproc"],
)

filegroup(
    name = "artifacts",
    testonly = True,
    srcs = [":test"],
)
